<?php
/**
 * Get Class Statistics API
 * Returns: students enrolled, average grade, average topics completed
 */

// CRITICAL: Set error reporting to prevent any output before JSON
error_reporting(E_ALL);
ini_set('display_errors', 0); // Don't display errors, log them instead
ini_set('log_errors', 1);

// Start output buffering to catch any unexpected output
ob_start();

// CRITICAL: Set JSON header FIRST to prevent any HTML output
header('Content-Type: application/json; charset=utf-8');

// Manual session handling (don't use unified_bootstrap which might redirect)
$sessionPath = __DIR__ . '/sessions';
if (!is_dir($sessionPath)) {
    @mkdir($sessionPath, 0777, true);
}
if (is_dir($sessionPath) && is_writable($sessionPath)) {
    ini_set('session.save_path', $sessionPath);
}

if (session_status() === PHP_SESSION_NONE) {
    $preferred = 'CodeRegalSession';
    $legacy = 'PHPSESSID';
    if (!empty($_COOKIE[$preferred])) { 
        session_name($preferred); 
    } elseif (!empty($_COOKIE[$legacy])) { 
        session_name($legacy); 
    } else { 
        session_name($preferred); 
    }
    @session_start();
    
    if (empty($_SESSION['user_id'])) {
        $current = session_name();
        $alt = ($current === $preferred) ? $legacy : $preferred;
        if (!empty($_COOKIE[$alt])) {
            @session_write_close();
            session_name($alt);
            @session_id($_COOKIE[$alt]);
            @session_start();
        }
    }
}

require_once __DIR__ . '/config/Database.php';

// Clean any output that might have been generated by includes
$obContent = ob_get_clean();
if (!empty($obContent) && trim($obContent) !== '') {
    // If there was output, log it but don't send it
    error_log("get_class_statistics.php - Unexpected output before JSON: " . substr($obContent, 0, 500));
    // Start fresh buffer
    ob_start();
}

// Manual authentication check (don't use requireAuth which redirects)
if (empty($_SESSION['user_id'])) {
    http_response_code(401);
    echo json_encode(['success' => false, 'message' => 'Unauthorized']);
    exit;
}

$userId = (int)($_SESSION['user_id'] ?? 0);
$userRole = strtolower((string)($_SESSION['user_role'] ?? 'student'));

if ($userRole !== 'teacher') {
    http_response_code(403);
    echo json_encode(['success' => false, 'message' => 'Access denied. Teacher only.']);
    exit;
}

$classId = isset($_GET['class_id']) ? (int)$_GET['class_id'] : 0;

if ($classId <= 0) {
    http_response_code(400);
    echo json_encode(['success' => false, 'message' => 'Invalid class ID']);
    exit;
}

try {
    $db = (new Database())->getConnection();
    
    // Verify teacher owns this class
    $stmt = $db->prepare("SELECT id FROM classes WHERE id = ? AND owner_user_id = ? AND status = 'active'");
    $stmt->execute([$classId, $userId]);
    if (!$stmt->fetch()) {
        http_response_code(403);
        echo json_encode(['success' => false, 'message' => 'Access denied']);
        exit;
    }
    
    // Check if status column exists in class_students
    $hasStatusColumn = false;
    try {
        $checkStmt = $db->query("SHOW COLUMNS FROM class_students LIKE 'status'");
        $hasStatusColumn = $checkStmt->rowCount() > 0;
    } catch (Exception $e) {
        // Column doesn't exist
    }
    
    // 1. Count Students Enrolled (ACCEPTED only)
    if ($hasStatusColumn) {
        $studentsStmt = $db->prepare("
            SELECT COUNT(DISTINCT cs.student_user_id) as total_students
            FROM class_students cs
            INNER JOIN users u ON cs.student_user_id = u.id
            WHERE cs.class_id = ? AND u.status = 'active' AND cs.status = 'accepted'
        ");
    } else {
        // Fallback for old schema
        $studentsStmt = $db->prepare("
            SELECT COUNT(DISTINCT cs.student_user_id) as total_students
            FROM class_students cs
            INNER JOIN users u ON cs.student_user_id = u.id
            WHERE cs.class_id = ? AND u.status = 'active'
        ");
    }
    $studentsStmt->execute([$classId]);
    $studentsCount = (int)$studentsStmt->fetchColumn();
    
    // 2. Calculate Average Grade
    // Get all activities for this class
    $activitiesStmt = $db->prepare("
        SELECT la.id, la.max_score
        FROM lesson_activities la
        INNER JOIN course_lessons cl ON la.lesson_id = cl.id
        INNER JOIN course_modules cm ON cl.module_id = cm.id
        INNER JOIN classes c ON cm.course_id = c.course_id
        WHERE c.id = ?
    ");
    $activitiesStmt->execute([$classId]);
    $activities = $activitiesStmt->fetchAll(PDO::FETCH_ASSOC);
    
    $averageGrade = null;
    if (!empty($activities)) {
        // Get all ACCEPTED students in class only (with joined_at date)
        if ($hasStatusColumn) {
            $classStudentsStmt = $db->prepare("
                SELECT DISTINCT cs.student_user_id, cs.joined_at
                FROM class_students cs
                INNER JOIN users u ON cs.student_user_id = u.id
                WHERE cs.class_id = ? AND u.status = 'active' AND cs.status = 'accepted'
            ");
        } else {
            // Fallback for old schema
            $classStudentsStmt = $db->prepare("
                SELECT DISTINCT cs.student_user_id, cs.joined_at
                FROM class_students cs
                INNER JOIN users u ON cs.student_user_id = u.id
                WHERE cs.class_id = ? AND u.status = 'active'
            ");
        }
        $classStudentsStmt->execute([$classId]);
        $students = $classStudentsStmt->fetchAll(PDO::FETCH_ASSOC);
        
        if (!empty($students)) {
            $totalScores = [];
            $totalMaxScores = [];
            
            foreach ($students as $studentRow) {
                $studentId = (int)$studentRow['student_user_id'];
                $joinedAt = $studentRow['joined_at'] ?? null;
                
                $studentTotalScore = 0;
                $studentMaxScore = 0;
                
                foreach ($activities as $activity) {
                    $activityId = $activity['id'];
                    $maxScore = (int)$activity['max_score'];
                    
                    // Get best attempt score for this student and activity (use user_id, role='student', is_preview=0)
                    // CRITICAL: Only count attempts submitted AFTER the student joined this class
                    $scoreParams = [$activityId, $studentId];
                    $scoreWhere = "
                        WHERE activity_id = ? 
                        AND user_id = ? 
                        AND role = 'student' 
                        AND is_preview = 0
                        AND submitted_at IS NOT NULL
                        AND score IS NOT NULL
                    ";
                    
                    // Filter by joined_at date if available
                    if ($joinedAt) {
                        $scoreWhere .= " AND DATE(submitted_at) >= DATE(?)";
                        $scoreParams[] = $joinedAt;
                    }
                    
                    $scoreStmt = $db->prepare("
                        SELECT MAX(score) as best_score
                        FROM activity_attempts
                        $scoreWhere
                    ");
                    $scoreStmt->execute($scoreParams);
                    $bestScore = $scoreStmt->fetchColumn();
                    
                    // Always count max score (even if no attempt, student gets 0)
                    $studentMaxScore += $maxScore;
                    
                    // If we have a score (including 0), add it to total
                    if ($bestScore !== false && $bestScore !== null) {
                        $studentTotalScore += (float)$bestScore;
                    }
                    // If no score, studentTotalScore stays 0 (which is correct)
                }
                
                if ($studentMaxScore > 0) {
                    $percentage = ($studentTotalScore / $studentMaxScore) * 100;
                    $totalScores[] = $percentage;
                }
            }
            
            if (!empty($totalScores)) {
                $averageGrade = round(array_sum($totalScores) / count($totalScores), 1);
            }
        }
    }
    
    // 3. Calculate Average Topics Completed
    // Get all lessons/topics for this class
    $lessonsStmt = $db->prepare("
        SELECT cl.id as lesson_id
        FROM course_lessons cl
        INNER JOIN course_modules cm ON cl.module_id = cm.id
        INNER JOIN classes c ON cm.course_id = c.course_id
        WHERE c.id = ?
    ");
    $lessonsStmt->execute([$classId]);
    $lessons = $lessonsStmt->fetchAll(PDO::FETCH_COLUMN);
    
    $averageTopicsCompleted = null;
    if (!empty($lessons)) {
        // Get all ACCEPTED students in class only (with joined_at date)
        if ($hasStatusColumn) {
            $classStudentsStmt = $db->prepare("
                SELECT DISTINCT cs.student_user_id, cs.joined_at
                FROM class_students cs
                INNER JOIN users u ON cs.student_user_id = u.id
                WHERE cs.class_id = ? AND u.status = 'active' AND cs.status = 'accepted'
            ");
        } else {
            // Fallback for old schema
            $classStudentsStmt = $db->prepare("
                SELECT DISTINCT cs.student_user_id, cs.joined_at
                FROM class_students cs
                INNER JOIN users u ON cs.student_user_id = u.id
                WHERE cs.class_id = ? AND u.status = 'active'
            ");
        }
        $classStudentsStmt->execute([$classId]);
        $students = $classStudentsStmt->fetchAll(PDO::FETCH_ASSOC);
        
        if (!empty($students)) {
            $completionPercentages = [];
            
            foreach ($students as $studentRow) {
                $studentId = (int)$studentRow['student_user_id'];
                $joinedAt = $studentRow['joined_at'] ?? null;
                
                $completedLessons = 0;
                
                foreach ($lessons as $lessonId) {
                    // Check if student has completed at least one activity in this lesson
                    // CRITICAL: Only count activities completed AFTER the student joined this class
                    $completedParams = [$lessonId, $studentId];
                    $completedWhere = "
                        WHERE la.lesson_id = ? 
                        AND aa.user_id = ? 
                        AND aa.role = 'student' 
                        AND aa.is_preview = 0
                        AND aa.submitted_at IS NOT NULL
                        AND (aa.score IS NOT NULL OR la.type IN ('essay', 'upload_based'))
                    ";
                    
                    // Filter by joined_at date if available
                    if ($joinedAt) {
                        $completedWhere .= " AND DATE(aa.submitted_at) >= DATE(?)";
                        $completedParams[] = $joinedAt;
                    }
                    
                    $completedStmt = $db->prepare("
                        SELECT COUNT(DISTINCT la.id) as completed
                        FROM lesson_activities la
                        INNER JOIN activity_attempts aa ON la.id = aa.activity_id
                        $completedWhere
                    ");
                    $completedStmt->execute($completedParams);
                    $completed = (int)$completedStmt->fetchColumn();
                    
                    if ($completed > 0) {
                        $completedLessons++;
                    }
                }
                
                if (count($lessons) > 0) {
                    $percentage = ($completedLessons / count($lessons)) * 100;
                    $completionPercentages[] = $percentage;
                }
            }
            
            if (!empty($completionPercentages)) {
                $averageTopicsCompleted = round(array_sum($completionPercentages) / count($completionPercentages), 1);
            }
        }
    }
    
    // Clean output buffer before sending final response
    while (ob_get_level()) {
        ob_end_clean();
    }
    
    echo json_encode([
        'success' => true,
        'data' => [
            'students_enrolled' => $studentsCount,
            'average_grade' => $averageGrade,
            'average_topics_completed' => $averageTopicsCompleted
        ]
    ]);
    exit;
    
} catch (Exception $e) {
    error_log("Error getting class statistics: " . $e->getMessage());
    
    // Clean any output before sending error
    while (ob_get_level()) {
        ob_end_clean();
    }
    
    http_response_code(500);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode([
        'success' => false,
        'message' => 'Failed to get class statistics',
        'error' => $e->getMessage()
    ]);
    exit;
}

?>

