<?php
/**
 * GET ACTIVITY SUBMISSIONS API
 * Returns all student submissions for an activity (for teacher grading)
 */

// CRITICAL: Set error reporting to prevent any output before JSON
error_reporting(E_ALL);
ini_set('display_errors', 0); // Don't display errors, log them instead
ini_set('log_errors', 1);

// Start output buffering to catch any unexpected output
ob_start();

// CRITICAL: Set JSON header FIRST to prevent any HTML output
header('Content-Type: application/json; charset=utf-8');

// Manual session handling (don't use unified_bootstrap which might redirect)
$sessionPath = __DIR__ . '/sessions';
if (!is_dir($sessionPath)) {
    @mkdir($sessionPath, 0777, true);
}
if (is_dir($sessionPath) && is_writable($sessionPath)) {
    ini_set('session.save_path', $sessionPath);
}

if (session_status() === PHP_SESSION_NONE) {
    $preferred = 'CodeRegalSession';
    $legacy = 'PHPSESSID';
    if (!empty($_COOKIE[$preferred])) { 
        session_name($preferred); 
    } elseif (!empty($_COOKIE[$legacy])) { 
        session_name($legacy); 
    } else { 
        session_name($preferred); 
    }
    @session_start();
    
    if (empty($_SESSION['user_id'])) {
        $current = session_name();
        $alt = ($current === $preferred) ? $legacy : $preferred;
        if (!empty($_COOKIE[$alt])) {
            @session_write_close();
            session_name($alt);
            @session_id($_COOKIE[$alt]);
            @session_start();
        }
    }
}

require_once __DIR__ . '/config/Database.php';

// Clean any output that might have been generated by includes
$obContent = ob_get_clean();
if (!empty($obContent) && trim($obContent) !== '') {
    // If there was output, log it but don't send it
    error_log("get_activity_submissions.php - Unexpected output before JSON: " . substr($obContent, 0, 500));
    // Start fresh buffer
    ob_start();
}

try {
    // Manual authentication check (don't use requireAuth which redirects)
    if (!isset($_SESSION['user_id']) || empty($_SESSION['user_id'])) {
        // Ensure clean output
        if (ob_get_level()) {
            ob_clean();
        }
        http_response_code(401);
        header('Content-Type: application/json; charset=utf-8');
        echo json_encode([
            'success' => false,
            'message' => 'Unauthorized - Please log in'
        ]);
        exit;
    }
    
    $userId = (int)($_SESSION['user_id'] ?? 0);
    if ($userId <= 0) {
        throw new Exception('User not authenticated');
    }
    
    // Check user role (only teachers, coordinators, admins can view submissions)
    $db = (new Database())->getConnection();
    $roleStmt = $db->prepare("SELECT LOWER(TRIM(role)) FROM users WHERE id=? LIMIT 1");
    $roleStmt->execute([$userId]);
    $role = $roleStmt->fetchColumn() ?: '';
    
    if (!in_array($role, ['teacher', 'coordinator', 'admin'], true)) {
        throw new Exception('Forbidden - Only teachers can view submissions');
    }
    
    $activityId = (int)($_GET['activity_id'] ?? 0);
    if ($activityId <= 0) {
        throw new Exception('Invalid activity ID');
    }
    
    // Verify teacher owns a class that contains this activity
    if ($role === 'teacher' && $role !== 'admin' && $role !== 'coordinator') {
        $checkStmt = $db->prepare("
            SELECT c.id 
            FROM classes c
            INNER JOIN course_modules cm ON cm.course_id = c.course_id
            INNER JOIN course_lessons cl ON cl.module_id = cm.id
            INNER JOIN lesson_activities la ON la.lesson_id = cl.id
            WHERE la.id = ? AND c.owner_user_id = ? AND c.status = 'active'
            LIMIT 1
        ");
        $checkStmt->execute([$activityId, $userId]);
        if (!$checkStmt->fetch()) {
            throw new Exception('You do not have permission to view submissions for this activity');
        }
    }
    
    // Get all submissions for this activity
    $stmt = $db->prepare("
        SELECT 
            aa.id as attempt_id,
            aa.user_id,
            aa.score,
            aa.submitted_at,
            aa.time_spent_ms,
            u.firstname,
            u.middlename,
            u.lastname,
            u.id_number
        FROM activity_attempts aa
        INNER JOIN users u ON u.id = aa.user_id
        WHERE aa.activity_id = ? AND aa.submitted_at IS NOT NULL
        ORDER BY aa.submitted_at DESC
    ");
    $stmt->execute([$activityId]);
    $submissions = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    // Get attempt items for each submission
    $result = [];
    foreach ($submissions as $sub) {
        $attemptId = (int)$sub['attempt_id'];
        
        // Get attempt items for this submission
        $itemsStmt = $db->prepare("
            SELECT 
                id as item_id,
                question_id,
                response_text,
                points_awarded,
                is_correct,
                extra
            FROM activity_attempt_items
            WHERE attempt_id = ?
            ORDER BY id ASC
        ");
        $itemsStmt->execute([$attemptId]);
        $items = $itemsStmt->fetchAll(PDO::FETCH_ASSOC);
        
        // DEBUG: Log what we found
        error_log("=== DEBUG: Attempt {$attemptId} ===");
        error_log("Attempt {$attemptId} - Found " . count($items) . " items");
        
        // Also check if there are ANY items for this attempt_id (double-check)
        $countStmt = $db->prepare("SELECT COUNT(*) FROM activity_attempt_items WHERE attempt_id = ?");
        $countStmt->execute([$attemptId]);
        $itemCount = (int)$countStmt->fetchColumn();
        error_log("Attempt {$attemptId} - Direct COUNT query: {$itemCount} items");
        
        // If count doesn't match, log all items for this attempt
        if ($itemCount > 0 && count($items) === 0) {
            error_log("WARNING: COUNT says {$itemCount} items but fetchAll returned 0!");
            $allItemsStmt = $db->prepare("SELECT * FROM activity_attempt_items WHERE attempt_id = ?");
            $allItemsStmt->execute([$attemptId]);
            $allItems = $allItemsStmt->fetchAll(PDO::FETCH_ASSOC);
            error_log("Attempt {$attemptId} - Raw items: " . json_encode($allItems));
        }
        
        foreach ($items as $idx => $item) {
            error_log("Attempt {$attemptId} - Item {$idx}: question_id={$item['question_id']}, response_text length=" . strlen($item['response_text'] ?? '') . ", extra=" . ($item['extra'] ?? 'null'));
            if (!empty($item['response_text'])) {
                error_log("Attempt {$attemptId} - Item {$idx} response_text preview: " . substr($item['response_text'], 0, 200));
                error_log("Attempt {$attemptId} - Item {$idx} response_text FULL: " . $item['response_text']);
            }
        }
        
        // Get activity type and instructions to determine if it's upload-based, essay, or identification
        // Note: We'll get the global activity type later, but for per-submission parsing we need it here
        $activityStmt = $db->prepare("SELECT type, instructions FROM lesson_activities WHERE id = ? LIMIT 1");
        $activityStmt->execute([$activityId]);
        $activityData = $activityStmt->fetch(PDO::FETCH_ASSOC);
        $perSubmissionActivityType = strtolower(trim($activityData['type'] ?? '')); // Per-submission activity type
        $activityInstructions = $activityData['instructions'] ?? '';
        
        // Parse activity instructions (may be JSON)
        $parsedInstructions = null;
        if (!empty($activityInstructions)) {
            try {
                $decoded = json_decode($activityInstructions, true);
                if (json_last_error() === JSON_ERROR_NONE && is_array($decoded)) {
                    $parsedInstructions = $decoded;
                } else {
                    $parsedInstructions = $activityInstructions; // Plain text
                }
            } catch (Exception $e) {
                $parsedInstructions = $activityInstructions; // Plain text
            }
        }
        
        // Get question text for essay activities
        $questionText = null;
        $questionId = null;
        if ($perSubmissionActivityType === 'essay' && !empty($items)) {
            // Get question_id from first item
            $firstItem = $items[0];
            $questionId = (int)($firstItem['question_id'] ?? 0);
            
            if ($questionId > 0) {
                // Get question text from activity_questions
                $questionStmt = $db->prepare("SELECT question_text FROM activity_questions WHERE id = ? LIMIT 1");
                $questionStmt->execute([$questionId]);
                $questionText = $questionStmt->fetchColumn() ?: null;
                error_log("Found question text for attempt {$attemptId}, question_id: {$questionId}, text length: " . ($questionText ? strlen($questionText) : 0));
            }
        }
        
        // Parse upload file info OR essay text from response_text
        $uploadInfo = null;
        $essayText = null;
        
        if (!empty($items)) {
            // Try to find file info or essay text in any item
            foreach ($items as $item) {
                if (!empty($item['response_text'])) {
                    try {
                        $uploadData = json_decode($item['response_text'], true);
                        if (json_last_error() === JSON_ERROR_NONE && is_array($uploadData)) {
                            // Check if this looks like file upload data
                            if (isset($uploadData['filePath']) || isset($uploadData['file_path']) || 
                                isset($uploadData['fileName']) || isset($uploadData['file_name'])) {
                                // Normalize keys (support both camelCase and snake_case)
                                $uploadInfo = [
                                    'fileName' => $uploadData['fileName'] ?? $uploadData['file_name'] ?? 'uploaded_file',
                                    'fileSize' => $uploadData['fileSize'] ?? $uploadData['file_size'] ?? 0,
                                    'fileType' => $uploadData['fileType'] ?? $uploadData['file_type'] ?? '',
                                    'filePath' => $uploadData['filePath'] ?? $uploadData['file_path'] ?? ''
                                ];
                                error_log("Found upload info for attempt {$attemptId}: " . json_encode($uploadInfo));
                                break; // Found it, stop searching
                            }
                        } else {
                            // Check if it's a plain text file path
                            $text = trim($item['response_text']);
                            if (strpos($text, 'download_activity_file.php') !== false || 
                                strpos($text, 'activity_submissions') !== false) {
                                // It's a file path, construct upload info
                                $uploadInfo = [
                                    'fileName' => basename($text),
                                    'fileSize' => 0,
                                    'fileType' => '',
                                    'filePath' => $text
                                ];
                                error_log("Found file path in plain text for attempt {$attemptId}: {$text}");
                                break;
                            } else if ($perSubmissionActivityType === 'essay') {
                                // For essay activities, the response_text is the essay content
                                $essayText = $text;
                                error_log("Found essay text for attempt {$attemptId}, length: " . strlen($essayText));
                                break;
                            }
                        }
                    } catch (Exception $e) {
                        error_log("Error parsing upload/essay data for attempt {$attemptId}: " . $e->getMessage());
                    }
                }
            }
            
            // If no essay text found yet and it's an essay activity, try to get it from items
            if ($perSubmissionActivityType === 'essay' && !$essayText && !empty($items)) {
                foreach ($items as $item) {
                    if (!empty($item['response_text'])) {
                        $text = trim($item['response_text']);
                        // If it's not JSON and not a file path, it's likely the essay text
                        if (!json_decode($text, true) && 
                            strpos($text, 'download_activity_file.php') === false &&
                            strpos($text, 'activity_submissions') === false) {
                            $essayText = $text;
                            error_log("Found essay text (fallback) for attempt {$attemptId}, length: " . strlen($essayText));
                            break;
                        }
                    }
                }
            }
        } else {
            error_log("No items found for attempt {$attemptId}");
        }
        
        if (!$uploadInfo && !$essayText) {
            error_log("No upload info or essay text found for attempt {$attemptId} - items count: " . count($items) . ", activity type: {$perSubmissionActivityType}");
        }
        
        $result[] = [
            'attempt_id' => (int)$sub['attempt_id'],
            'user_id' => (int)$sub['user_id'],
            'student_name' => trim(($sub['lastname'] ?? '') . ', ' . ($sub['firstname'] ?? '') . (!empty($sub['middlename']) ? ' ' . substr($sub['middlename'], 0, 1) . '.' : '')),
            'id_number' => $sub['id_number'] ?? '',
            'score' => $sub['score'] !== null ? (float)$sub['score'] : null,
            'max_score' => null, // Will be set from activity
            'submitted_at' => $sub['submitted_at'],
            'time_spent_ms' => $sub['time_spent_ms'] ? (int)$sub['time_spent_ms'] : null,
            'upload_info' => $uploadInfo,
            'essay_text' => $essayText,
            'essay_question' => $questionText,
            'activity_instructions' => $parsedInstructions,
            'items' => $items
        ];
    }
    
    // Get activity max score, instructions, and type (for all submissions)
    $activityStmt = $db->prepare("SELECT max_score, instructions, type FROM lesson_activities WHERE id = ? LIMIT 1");
    $activityStmt->execute([$activityId]);
    $activityData = $activityStmt->fetch(PDO::FETCH_ASSOC);
    $maxScore = $activityData['max_score'] ?? null;
    $globalInstructions = $activityData['instructions'] ?? '';
    $activityType = strtolower(trim($activityData['type'] ?? ''));
    
    // Parse global instructions
    $parsedGlobalInstructions = null;
    if (!empty($globalInstructions)) {
        try {
            $decoded = json_decode($globalInstructions, true);
            if (json_last_error() === JSON_ERROR_NONE && is_array($decoded)) {
                $parsedGlobalInstructions = $decoded;
            } else {
                $parsedGlobalInstructions = $globalInstructions; // Plain text
            }
        } catch (Exception $e) {
            $parsedGlobalInstructions = $globalInstructions; // Plain text
        }
    }
    
    // Get all questions for essay activities (to show in all submissions)
    $allQuestions = [];
    if ($activityType === 'essay') {
        $questionsStmt = $db->prepare("SELECT id, question_text, points FROM activity_questions WHERE activity_id = ? ORDER BY position ASC, id ASC");
        $questionsStmt->execute([$activityId]);
        $allQuestions = $questionsStmt->fetchAll(PDO::FETCH_ASSOC);
        error_log("Found " . count($allQuestions) . " essay questions for activity {$activityId}");
    } else {
        error_log("Activity type is '{$activityType}' (not essay) for activity {$activityId}");
    }
    
    if ($maxScore !== false && $maxScore !== null) {
        foreach ($result as &$sub) {
            $sub['max_score'] = (float)$maxScore;
        }
    }
    
    // Add global instructions and questions to all submissions if not already set
    foreach ($result as &$sub) {
        if (!isset($sub['activity_instructions']) || $sub['activity_instructions'] === null) {
            $sub['activity_instructions'] = $parsedGlobalInstructions;
        }
        if (!isset($sub['essay_question']) && !empty($allQuestions)) {
            // Use first question if essay_question not set
            $sub['essay_question'] = $allQuestions[0]['question_text'] ?? null;
        }
    }
    
    echo json_encode([
        'success' => true,
        'submissions' => $result,
        'activity_instructions' => $parsedGlobalInstructions,
        'essay_questions' => $allQuestions
    ]);
    
} catch (Exception $e) {
    error_log("Get activity submissions error: " . $e->getMessage());
    error_log("Get activity submissions error stack: " . $e->getTraceAsString());
    
    // Ensure we output clean JSON even on errors
    if (ob_get_level()) {
        ob_clean();
    }
    
    http_response_code(400);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode([
        'success' => false,
        'message' => $e->getMessage()
    ]);
    exit;
}
?>

