<?php
/**
 * GET STUDENT SCORE API
 * Gets the student's best/final score from activity_attempts (not draft progress)
 */

// CRITICAL: Set session path BEFORE any session_start() calls
$sessionPath = __DIR__ . '/sessions';
if (!is_dir($sessionPath)) {
    @mkdir($sessionPath, 0777, true);
}
if (is_dir($sessionPath) && is_writable($sessionPath)) {
    ini_set('session.save_path', $sessionPath);
}

// Start session if not already started - use same logic as main app
if (session_status() === PHP_SESSION_NONE) {
    // Try to use the same session name as the main app
    $preferred = 'CodeRegalSession';
    $legacy = 'PHPSESSID';
    if (!empty($_COOKIE[$preferred])) { 
        session_name($preferred); 
    } elseif (!empty($_COOKIE[$legacy])) { 
        session_name($legacy); 
    } else { 
        session_name($preferred); 
    }
    @session_start();
    
    // If still no user_id, try alternate session name
    if (empty($_SESSION['user_id'])) {
        $current = session_name();
        $alt = ($current === $preferred) ? $legacy : $preferred;
        if (!empty($_COOKIE[$alt])) {
            @session_write_close();
            session_name($alt);
            @session_id($_COOKIE[$alt]);
            @session_start();
        }
    }
}

// CRITICAL: Set error reporting to prevent any output before JSON
error_reporting(E_ALL);
ini_set('display_errors', 0); // Don't display errors, log them instead
ini_set('log_errors', 1);

// Start output buffering to catch any unexpected output
ob_start();

require_once __DIR__ . '/config/Database.php';
require_once __DIR__ . '/classes/auth_helpers.php';
require_once __DIR__ . '/classes/ActivityAttemptService.php';

// CRITICAL: Set JSON header and prevent any output before JSON
header('Content-Type: application/json; charset=utf-8');

// Clean any output that might have been generated by includes
$obContent = ob_get_clean();
if (!empty($obContent) && trim($obContent) !== '') {
    // If there was output, log it but don't send it
    error_log("get_student_score.php - Unexpected output before JSON: " . substr($obContent, 0, 500));
    // Start fresh buffer
    ob_start();
}

try {
    $db = (new Database())->getConnection();
    if (!$db) {
        throw new Exception('Database connection failed');
    }
    
    // Check authentication without redirecting (for API endpoints)
    if (!isset($_SESSION['user_id']) || empty($_SESSION['user_id'])) {
        // Ensure clean output
        if (ob_get_level()) {
            ob_clean();
        }
        http_response_code(401);
        header('Content-Type: application/json; charset=utf-8');
        echo json_encode([
            'success' => false,
            'score' => 0,
            'attempt_id' => null,
            'submitted_at' => null,
            'is_pending' => false,
            'is_manual_grading' => false,
            'message' => 'Unauthorized'
        ]);
        exit;
    }
    
    $userId = (int)($_SESSION['user_id'] ?? 0);
    if ($userId <= 0) {
        throw new Exception('User not authenticated');
    }
    
    $activityId = (int)($_GET['activity_id'] ?? 0);
    if ($activityId <= 0) {
        throw new Exception('Invalid activity ID');
    }
    
    // Get optional class_id parameter (for filtering attempts by joined_at date)
    $classId = isset($_GET['class_id']) ? (int)$_GET['class_id'] : null;
    if ($classId !== null && $classId <= 0) {
        $classId = null; // Treat invalid class_id as null
    }
    
    // Get activity type to check if it's manual grading
    // Also get title and instructions to help detect essay activities
    $activityStmt = $db->prepare("SELECT type, title, instructions FROM lesson_activities WHERE id = ? LIMIT 1");
    $activityStmt->execute([$activityId]);
    $activityData = $activityStmt->fetch(PDO::FETCH_ASSOC);
    $activityType = strtolower(trim($activityData['type'] ?? ''));
    $activityTitle = strtolower(trim($activityData['title'] ?? ''));
    $activityInstructions = $activityData['instructions'] ?? '';
    
    // Check if it's an essay activity - multiple ways to detect:
    // 1. Type is explicitly 'essay'
    // 2. Title contains 'essay'
    // 3. Instructions might indicate essay type
    // 4. Check questions - essay activities typically have questions with no choices
    $isEssay = ($activityType === 'essay') || 
               (strpos($activityTitle, 'essay') !== false) ||
               (stripos($activityInstructions, 'essay') !== false);
    
    // Additional check: Look at questions to detect essay
    // Essay activities typically have questions with no multiple choice options
    if (!$isEssay) {
        $questionsStmt = $db->prepare("SELECT COUNT(*) as q_count FROM activity_questions WHERE activity_id = ?");
        $questionsStmt->execute([$activityId]);
        $questionCount = (int)$questionsStmt->fetchColumn();
        
        if ($questionCount > 0) {
            // Check if questions have choices - essay questions typically don't have choices
            $choicesStmt = $db->prepare("
                SELECT COUNT(DISTINCT qc.question_id) as questions_with_choices
                FROM question_choices qc
                INNER JOIN activity_questions aq ON qc.question_id = aq.id
                WHERE aq.activity_id = ?
            ");
            $choicesStmt->execute([$activityId]);
            $questionsWithChoices = (int)$choicesStmt->fetchColumn();
            
            // If there are questions but none have choices, it's likely an essay activity
            if ($questionsWithChoices == 0 && $questionCount > 0) {
                $isEssay = true;
                error_log("get_student_score.php - Activity {$activityId}: Detected as essay based on questions (has {$questionCount} questions but no choices)");
            }
        }
    }
    
    // Final fallback: Check submitted attempts - essay activities have text responses (not file paths)
    // This is a last resort if other detection methods fail
    if (!$isEssay && !$isManualGrading) {
        $attemptCheckStmt = $db->prepare("
            SELECT COUNT(*) as attempt_count
            FROM activity_attempts 
            WHERE activity_id = ? 
                AND submitted_at IS NOT NULL
            LIMIT 1
        ");
        $attemptCheckStmt->execute([$activityId]);
        $hasSubmissions = ((int)$attemptCheckStmt->fetchColumn()) > 0;
        
        if ($hasSubmissions) {
            // Check if any attempt items have text responses (not file paths)
            $responseCheckStmt = $db->prepare("
                SELECT COUNT(*) as text_response_count
                FROM activity_attempt_items aai
                INNER JOIN activity_attempts aa ON aai.attempt_id = aa.id
                WHERE aa.activity_id = ?
                    AND aa.submitted_at IS NOT NULL
                    AND aai.response_text IS NOT NULL
                    AND aai.response_text != ''
                    AND aai.response_text NOT LIKE '%download_activity_file.php%'
                    AND aai.response_text NOT LIKE '%activity_submissions%'
                    AND LENGTH(aai.response_text) > 50
                LIMIT 1
            ");
            $responseCheckStmt->execute([$activityId]);
            $hasTextResponses = ((int)$responseCheckStmt->fetchColumn()) > 0;
            
            if ($hasTextResponses) {
                // Has text responses but not file paths - likely essay
                // But be careful - identification also has text responses
                // Only treat as essay if it's NOT identification
                if ($activityType !== 'identification') {
                    $isEssay = true;
                    error_log("get_student_score.php - Activity {$activityId}: Detected as essay based on text responses in submissions");
                }
            }
        }
    }
    
    // Manual grading activities: essay OR upload_based
    $isManualGrading = $isEssay || ($activityType === 'upload_based');
    
    error_log("get_student_score.php - Activity {$activityId}, User {$userId}: Type = '{$activityType}', Title = '{$activityTitle}', isEssay = " . ($isEssay ? 'true' : 'false') . ", isManualGrading = " . ($isManualGrading ? 'true' : 'false'));
    
    // Get best attempt score from ActivityAttemptService
    // CRITICAL: Pass class_id to filter attempts by joined_at date (only count attempts after joining this class)
    $attemptService = new ActivityAttemptService($db);
    $bestAttempt = $attemptService->getUserBestAttempt($activityId, $userId, $classId);
    
    if ($bestAttempt) {
        $scoreValue = $bestAttempt['score'];
        $scoreIsNull = ($scoreValue === null);
        $scoreIsZero = ($scoreValue === 0 || $scoreValue === '0' || $scoreValue === 0.0);
        
        error_log("get_student_score.php - Activity {$activityId}, User {$userId}: Found attempt {$bestAttempt['id']}, score = " . var_export($scoreValue, true) . ", isNull = " . ($scoreIsNull ? 'true' : 'false') . ", isZero = " . ($scoreIsZero ? 'true' : 'false') . ", isManualGrading = " . ($isManualGrading ? 'true' : 'false'));
        
        // CRITICAL: For manual grading activities (essay OR upload_based), if score is 0 or NULL and there's a submitted attempt,
        // it's definitely pending (not graded yet). Manual grading activities should never have score=0 unless explicitly graded as 0.
        // For essay and upload_based, score=0 with a submission means it's pending, not actually graded as 0.
        $shouldTreatAsPending = false;
        if ($isManualGrading && $bestAttempt['submitted_at']) {
            // For manual grading activities, if score is NULL or 0, it's pending
            if ($scoreIsNull) {
                $shouldTreatAsPending = true;
                error_log("get_student_score.php - Activity {$activityId}, User {$userId}: Manual grading with NULL score - treating as PENDING");
            } else if ($scoreIsZero) {
                // Check if there are any attempt items that might indicate it's actually pending
                $itemsStmt = $db->prepare("SELECT COUNT(*) as item_count, SUM(CASE WHEN points_awarded IS NULL THEN 1 ELSE 0 END) as null_points_count FROM activity_attempt_items WHERE attempt_id = ?");
                $itemsStmt->execute([$bestAttempt['id']]);
                $itemsData = $itemsStmt->fetch(PDO::FETCH_ASSOC);
                $hasNullPoints = ($itemsData['null_points_count'] > 0);
                
                // If there are items with NULL points_awarded, it's definitely pending
                if ($hasNullPoints) {
                    $shouldTreatAsPending = true;
                    error_log("get_student_score.php - Activity {$activityId}, User {$userId}: Manual grading with score=0 and NULL points_awarded items - treating as PENDING");
                } else {
                    // For essay/upload_based, score=0 with submission is likely pending (not actually graded as 0)
                    // Only treat as pending if it's been submitted recently (within last 24 hours) or if we can't determine
                    // For now, be conservative: if it's manual grading and score is 0, treat as pending
                    $shouldTreatAsPending = true;
                    error_log("get_student_score.php - Activity {$activityId}, User {$userId}: Manual grading ({$activityType}) with score=0 - treating as PENDING (likely ungraded, not actually scored as 0)");
                }
            }
        }
        
        // CRITICAL: For manual grading activities, if there's a submission and score is 0 or NULL, it's ALWAYS pending
        // Only return graded if score is > 0 AND it's not manual grading
        $isGraded = (!$scoreIsNull && !$shouldTreatAsPending && !$isManualGrading) || 
                   ($isManualGrading && !$scoreIsNull && $scoreValue > 0);
        
        if ($isGraded) {
            // Has score - graded (score > 0 for manual grading, or any score for auto-graded)
            error_log("get_student_score.php - Activity {$activityId}, User {$userId}: Returning GRADED score = {$scoreValue}");
            echo json_encode([
                'success' => true,
                'score' => (float)$scoreValue,
                'attempt_id' => $bestAttempt['id'],
                'submitted_at' => $bestAttempt['submitted_at'],
                'is_pending' => false,
                'is_manual_grading' => $isManualGrading
            ]);
        } else {
            // Submitted but not graded yet (pending) - either NULL score or 0 for manual grading
            // CRITICAL: For manual grading activities with submission, ALWAYS pending if score is 0 or NULL
            $finalIsPending = $isManualGrading || $shouldTreatAsPending;
            
            error_log("get_student_score.php - Activity {$activityId}, User {$userId}: Returning PENDING (score is " . ($scoreIsNull ? 'null' : var_export($scoreValue, true)) . ", isManualGrading = " . ($isManualGrading ? 'true' : 'false') . ", shouldTreatAsPending = " . ($shouldTreatAsPending ? 'true' : 'false') . ", finalIsPending = " . ($finalIsPending ? 'true' : 'false') . ")");
            
            // CRITICAL: Force is_pending=true for manual grading activities with submissions
            if ($isManualGrading && $bestAttempt['submitted_at']) {
                $finalIsPending = true;
                error_log("get_student_score.php - Activity {$activityId}, User {$userId}: FORCING is_pending=true because isManualGrading=true AND has submission");
            }
            
            echo json_encode([
                'success' => true,
                'score' => null, // Always return null for pending
                'attempt_id' => $bestAttempt['id'],
                'submitted_at' => $bestAttempt['submitted_at'],
                'is_pending' => $finalIsPending, // Pending if manual grading or should treat as pending
                'is_manual_grading' => $isManualGrading
            ]);
        }
    } else {
        // No submitted attempt yet, return 0
        error_log("get_student_score.php - Activity {$activityId}, User {$userId}: No attempt found, returning score = 0");
        echo json_encode([
            'success' => true,
            'score' => 0,
            'attempt_id' => null,
            'submitted_at' => null,
            'is_pending' => false,
            'is_manual_grading' => $isManualGrading
        ]);
    }
    
} catch (Exception $e) {
    error_log("Get student score error: " . $e->getMessage());
    error_log("Get student score error stack: " . $e->getTraceAsString());
    
    // Ensure we output clean JSON even on errors
    if (ob_get_level()) {
        ob_clean();
    }
    
    http_response_code(400);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode([
        'success' => false,
        'score' => 0,
        'attempt_id' => null,
        'submitted_at' => null,
        'is_pending' => false,
        'is_manual_grading' => false,
        'message' => $e->getMessage()
    ]);
    exit;
}
?>

