<?php
/**
 * GRADE ACTIVITY SUBMISSION API
 * Allows teachers to grade upload-based and essay activities
 */

// CRITICAL: Set error reporting to prevent any output before JSON
error_reporting(E_ALL);
ini_set('display_errors', 0); // Don't display errors, log them instead
ini_set('log_errors', 1);

// Start output buffering to catch any unexpected output
ob_start();

// CRITICAL: Set JSON header FIRST to prevent any HTML output
header('Content-Type: application/json; charset=utf-8');

// Manual session handling (don't use unified_bootstrap which might redirect)
$sessionPath = __DIR__ . '/sessions';
if (!is_dir($sessionPath)) {
    @mkdir($sessionPath, 0777, true);
}
if (is_dir($sessionPath) && is_writable($sessionPath)) {
    ini_set('session.save_path', $sessionPath);
}

if (session_status() === PHP_SESSION_NONE) {
    $preferred = 'CodeRegalSession';
    $legacy = 'PHPSESSID';
    if (!empty($_COOKIE[$preferred])) { 
        session_name($preferred); 
    } elseif (!empty($_COOKIE[$legacy])) { 
        session_name($legacy); 
    } else { 
        session_name($preferred); 
    }
    @session_start();
    
    if (empty($_SESSION['user_id'])) {
        $current = session_name();
        $alt = ($current === $preferred) ? $legacy : $preferred;
        if (!empty($_COOKIE[$alt])) {
            @session_write_close();
            session_name($alt);
            @session_id($_COOKIE[$alt]);
            @session_start();
        }
    }
}

require_once __DIR__ . '/config/Database.php';
require_once __DIR__ . '/classes/CSRFProtection.php';

// Clean any output that might have been generated by includes
$obContent = ob_get_clean();
if (!empty($obContent) && trim($obContent) !== '') {
    // If there was output, log it but don't send it
    error_log("grade_activity_submission.php - Unexpected output before JSON: " . substr($obContent, 0, 500));
    // Start fresh buffer
    ob_start();
}

try {
    // Manual authentication check (don't use requireAuth which redirects)
    if (!isset($_SESSION['user_id']) || empty($_SESSION['user_id'])) {
        // Ensure clean output
        if (ob_get_level()) {
            ob_clean();
        }
        http_response_code(401);
        header('Content-Type: application/json; charset=utf-8');
        echo json_encode([
            'success' => false,
            'message' => 'Unauthorized - Please log in'
        ]);
        exit;
    }
    
    $userId = (int)($_SESSION['user_id'] ?? 0);
    if ($userId <= 0) {
        throw new Exception('User not authenticated');
    }
    
    // Check user role (only teachers, coordinators, admins can grade)
    $db = (new Database())->getConnection();
    $roleStmt = $db->prepare("SELECT LOWER(TRIM(role)) FROM users WHERE id=? LIMIT 1");
    $roleStmt->execute([$userId]);
    $role = $roleStmt->fetchColumn() ?: '';
    
    if (!in_array($role, ['teacher', 'coordinator', 'admin'], true)) {
        throw new Exception('Forbidden - Only teachers can grade submissions');
    }
    
    // Get JSON input
    $input = json_decode(file_get_contents('php://input'), true);
    if (!$input) {
        throw new Exception('Invalid JSON input');
    }
    
    // CSRF validation
    $csrfToken = $input[CSRFProtection::getTokenName()] ?? '';
    if (!CSRFProtection::validateToken($csrfToken)) {
        throw new Exception('Invalid CSRF token');
    }
    
    $attemptId = (int)($input['attempt_id'] ?? 0);
    $score = isset($input['score']) ? (float)$input['score'] : null;
    $feedback = trim($input['feedback'] ?? '');
    $itemScores = $input['item_scores'] ?? []; // Array of {item_id, points_awarded}
    
    if ($attemptId <= 0) {
        throw new Exception('Invalid attempt ID');
    }
    
    // Get attempt details
    $attemptStmt = $db->prepare("
        SELECT aa.id, aa.activity_id, aa.user_id, aa.score
        FROM activity_attempts aa
        WHERE aa.id = ?
        LIMIT 1
    ");
    $attemptStmt->execute([$attemptId]);
    $attempt = $attemptStmt->fetch(PDO::FETCH_ASSOC);
    
    if (!$attempt) {
        throw new Exception('Attempt not found');
    }
    
    $activityId = (int)$attempt['activity_id'];
    
    // Verify teacher owns a class that contains this activity
    if ($role === 'teacher' && $role !== 'admin' && $role !== 'coordinator') {
        $checkStmt = $db->prepare("
            SELECT c.id 
            FROM classes c
            INNER JOIN course_modules cm ON cm.course_id = c.course_id
            INNER JOIN course_lessons cl ON cl.module_id = cm.id
            INNER JOIN lesson_activities la ON la.lesson_id = cl.id
            WHERE la.id = ? AND c.owner_user_id = ? AND c.status = 'active'
            LIMIT 1
        ");
        $checkStmt->execute([$activityId, $userId]);
        if (!$checkStmt->fetch()) {
            throw new Exception('You do not have permission to grade this submission');
        }
    }
    
    // Get activity type
    $activityStmt = $db->prepare("SELECT type, max_score FROM lesson_activities WHERE id = ? LIMIT 1");
    $activityStmt->execute([$activityId]);
    $activity = $activityStmt->fetch(PDO::FETCH_ASSOC);
    
    if (!$activity) {
        throw new Exception('Activity not found');
    }
    
    $activityType = strtolower($activity['type'] ?? '');
    $maxScore = (float)($activity['max_score'] ?? 0);
    
    // Validate score
    if ($score !== null) {
        if ($score < 0 || ($maxScore > 0 && $score > $maxScore)) {
            throw new Exception("Score must be between 0 and {$maxScore}");
        }
    }
    
    // Start transaction
    $db->beginTransaction();
    
    try {
        // Update attempt score
        if ($score !== null) {
            $updateStmt = $db->prepare("UPDATE activity_attempts SET score = ? WHERE id = ?");
            $updateStmt->execute([$score, $attemptId]);
        }
        
        // Update individual item scores if provided
        if (!empty($itemScores) && is_array($itemScores)) {
            foreach ($itemScores as $itemScore) {
                $itemId = (int)($itemScore['item_id'] ?? 0);
                $pointsAwarded = isset($itemScore['points_awarded']) ? (float)$itemScore['points_awarded'] : null;
                
                if ($itemId > 0) {
                    // Verify item belongs to this attempt
                    $itemCheckStmt = $db->prepare("SELECT id FROM activity_attempt_items WHERE id = ? AND attempt_id = ? LIMIT 1");
                    $itemCheckStmt->execute([$itemId, $attemptId]);
                    if ($itemCheckStmt->fetch()) {
                        // Update item score
                        $itemUpdateStmt = $db->prepare("
                            UPDATE activity_attempt_items 
                            SET points_awarded = ?, is_correct = ? 
                            WHERE id = ?
                        ");
                        // If points awarded > 0, mark as correct
                        $isCorrect = ($pointsAwarded !== null && $pointsAwarded > 0) ? 1 : 0;
                        $itemUpdateStmt->execute([$pointsAwarded, $isCorrect, $itemId]);
                    }
                }
            }
            
            // Recalculate total score from items if not explicitly provided
            if ($score === null) {
                $sumStmt = $db->prepare("
                    SELECT COALESCE(SUM(points_awarded), 0) 
                    FROM activity_attempt_items 
                    WHERE attempt_id = ?
                ");
                $sumStmt->execute([$attemptId]);
                $calculatedScore = (float)$sumStmt->fetchColumn();
                
                $updateStmt = $db->prepare("UPDATE activity_attempts SET score = ? WHERE id = ?");
                $updateStmt->execute([$calculatedScore, $attemptId]);
                $score = $calculatedScore;
            }
        }
        
        // Store feedback in extra field of attempt (if needed)
        if (!empty($feedback)) {
            // You can store feedback in a separate table or in activity_attempts.extra field
            // For now, we'll just log it
            error_log("Grading feedback for attempt {$attemptId}: {$feedback}");
        }
        
        $db->commit();
        
        echo json_encode([
            'success' => true,
            'score' => $score,
            'message' => 'Grade saved successfully'
        ]);
        
    } catch (Exception $e) {
        $db->rollBack();
        throw $e;
    }
    
} catch (Exception $e) {
    error_log("Grade activity submission error: " . $e->getMessage());
    error_log("Grade activity submission error stack: " . $e->getTraceAsString());
    
    // Ensure we output clean JSON even on errors
    if (ob_get_level()) {
        ob_clean();
    }
    
    http_response_code(400);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode([
        'success' => false,
        'message' => $e->getMessage()
    ]);
    exit;
}
?>


